# Screen resolution
WIDTH = 1920
HEIGHT = 1080

# Horizontal campaign image
WELCOME_CAMPAIGN_WIDTH = 1600
WELCOME_CAMPAIGN_HEIGHT = 900

# Vertical screen
VERTICAL_WIDTH = HEIGHT
VERTICAL_HEIGHT = WIDTH
VERTICAL_HEIGHT_BOTTOM = 600
VERTICAL_CAMPAIGN_WIDTH = 1050
VERTICAL_CAMPAIGN_HEIGHT = 1400
VERTICAL_HEIGHT_TOP = WIDTH - VERTICAL_HEIGHT_BOTTOM
INDEX = VERTICAL_WIDTH / WIDTH
Y_VERTICAL_CAMPAIGN = VERTICAL_HEIGHT_TOP
X_VERTICAL_CAMPAIGN = int(VERTICAL_CAMPAIGN_WIDTH * (Y_VERTICAL_CAMPAIGN / VERTICAL_CAMPAIGN_HEIGHT))
SIDE_BORDER_WIDTH = int((VERTICAL_WIDTH - X_VERTICAL_CAMPAIGN) / 2)
MOVE_SIDE_OBJECTS_RANGE_LEFT = 100
MOVE_SIDE_OBJECTS_RANGE_RIGHT = VERTICAL_WIDTH - MOVE_SIDE_OBJECTS_RANGE_LEFT
